/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class DClassWrapper */

#ifndef _Included_DClassWrapper
#define _Included_DClassWrapper
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
